resolver: lts-24.62

packages:
- '.'

extra-deps:
- git: https://github.com/m4lvin/cudd.git
  commit: c5f0fd8446827b1473ef18ea5dcc5d32a256e57d
- HasCacBDD-0.4.0.0
- decision-diagrams-0.2.0.0

allow-newer: true

allow-newer-deps:
- HasCacBDD
- decision-diagrams
